// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sendReceiveWeights.proto
#ifndef GRPC_sendReceiveWeights_2eproto__INCLUDED
#define GRPC_sendReceiveWeights_2eproto__INCLUDED

#include "sendReceiveWeights.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace params {

class WeightsPasser final {
 public:
  static constexpr char const* service_full_name() {
    return "params.WeightsPasser";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // rpc sendWeights (WeightsToServer) returns (WeightsToClient) {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::params::Parameters, ::params::Parameters>> streamWeights(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::params::Parameters, ::params::Parameters>>(streamWeightsRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::params::Parameters, ::params::Parameters>> AsyncstreamWeights(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::params::Parameters, ::params::Parameters>>(AsyncstreamWeightsRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::params::Parameters, ::params::Parameters>> PrepareAsyncstreamWeights(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::params::Parameters, ::params::Parameters>>(PrepareAsyncstreamWeightsRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::params::Parameters>> sendWeights(::grpc::ClientContext* context, const ::params::Parameters& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::params::Parameters>>(sendWeightsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::params::Parameters>> AsyncsendWeights(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::params::Parameters>>(AsyncsendWeightsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::params::Parameters>> PrepareAsyncsendWeights(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::params::Parameters>>(PrepareAsyncsendWeightsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // rpc sendWeights (WeightsToServer) returns (WeightsToClient) {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void streamWeights(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::params::Parameters,::params::Parameters>* reactor) = 0;
      #else
      virtual void streamWeights(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::params::Parameters,::params::Parameters>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void sendWeights(::grpc::ClientContext* context, const ::params::Parameters* request, ::grpc::ClientReadReactor< ::params::Parameters>* reactor) = 0;
      #else
      virtual void sendWeights(::grpc::ClientContext* context, const ::params::Parameters* request, ::grpc::experimental::ClientReadReactor< ::params::Parameters>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::params::Parameters, ::params::Parameters>* streamWeightsRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::params::Parameters, ::params::Parameters>* AsyncstreamWeightsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::params::Parameters, ::params::Parameters>* PrepareAsyncstreamWeightsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::params::Parameters>* sendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::params::Parameters>* AsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::params::Parameters>* PrepareAsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::params::Parameters, ::params::Parameters>> streamWeights(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::params::Parameters, ::params::Parameters>>(streamWeightsRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::params::Parameters, ::params::Parameters>> AsyncstreamWeights(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::params::Parameters, ::params::Parameters>>(AsyncstreamWeightsRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::params::Parameters, ::params::Parameters>> PrepareAsyncstreamWeights(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::params::Parameters, ::params::Parameters>>(PrepareAsyncstreamWeightsRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::params::Parameters>> sendWeights(::grpc::ClientContext* context, const ::params::Parameters& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::params::Parameters>>(sendWeightsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::params::Parameters>> AsyncsendWeights(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::params::Parameters>>(AsyncsendWeightsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::params::Parameters>> PrepareAsyncsendWeights(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::params::Parameters>>(PrepareAsyncsendWeightsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void streamWeights(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::params::Parameters,::params::Parameters>* reactor) override;
      #else
      void streamWeights(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::params::Parameters,::params::Parameters>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void sendWeights(::grpc::ClientContext* context, const ::params::Parameters* request, ::grpc::ClientReadReactor< ::params::Parameters>* reactor) override;
      #else
      void sendWeights(::grpc::ClientContext* context, const ::params::Parameters* request, ::grpc::experimental::ClientReadReactor< ::params::Parameters>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::params::Parameters, ::params::Parameters>* streamWeightsRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::params::Parameters, ::params::Parameters>* AsyncstreamWeightsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::params::Parameters, ::params::Parameters>* PrepareAsyncstreamWeightsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::params::Parameters>* sendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request) override;
    ::grpc::ClientAsyncReader< ::params::Parameters>* AsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::params::Parameters>* PrepareAsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_streamWeights_;
    const ::grpc::internal::RpcMethod rpcmethod_sendWeights_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // rpc sendWeights (WeightsToServer) returns (WeightsToClient) {}
    virtual ::grpc::Status streamWeights(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::params::Parameters, ::params::Parameters>* stream);
    virtual ::grpc::Status sendWeights(::grpc::ServerContext* context, const ::params::Parameters* request, ::grpc::ServerWriter< ::params::Parameters>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_streamWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_streamWeights() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_streamWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status streamWeights(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::params::Parameters, ::params::Parameters>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststreamWeights(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::params::Parameters, ::params::Parameters>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_sendWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_sendWeights() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_sendWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendWeights(::grpc::ServerContext* /*context*/, const ::params::Parameters* /*request*/, ::grpc::ServerWriter< ::params::Parameters>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendWeights(::grpc::ServerContext* context, ::params::Parameters* request, ::grpc::ServerAsyncWriter< ::params::Parameters>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_streamWeights<WithAsyncMethod_sendWeights<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_streamWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_streamWeights() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::params::Parameters, ::params::Parameters>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->streamWeights(context); }));
    }
    ~ExperimentalWithCallbackMethod_streamWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status streamWeights(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::params::Parameters, ::params::Parameters>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::params::Parameters, ::params::Parameters>* streamWeights(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::params::Parameters, ::params::Parameters>* streamWeights(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_sendWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_sendWeights() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::params::Parameters, ::params::Parameters>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::params::Parameters* request) { return this->sendWeights(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_sendWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendWeights(::grpc::ServerContext* /*context*/, const ::params::Parameters* /*request*/, ::grpc::ServerWriter< ::params::Parameters>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::params::Parameters>* sendWeights(
      ::grpc::CallbackServerContext* /*context*/, const ::params::Parameters* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::params::Parameters>* sendWeights(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::params::Parameters* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_streamWeights<ExperimentalWithCallbackMethod_sendWeights<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_streamWeights<ExperimentalWithCallbackMethod_sendWeights<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_streamWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_streamWeights() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_streamWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status streamWeights(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::params::Parameters, ::params::Parameters>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_sendWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_sendWeights() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_sendWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendWeights(::grpc::ServerContext* /*context*/, const ::params::Parameters* /*request*/, ::grpc::ServerWriter< ::params::Parameters>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_streamWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_streamWeights() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_streamWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status streamWeights(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::params::Parameters, ::params::Parameters>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststreamWeights(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_sendWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_sendWeights() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_sendWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendWeights(::grpc::ServerContext* /*context*/, const ::params::Parameters* /*request*/, ::grpc::ServerWriter< ::params::Parameters>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendWeights(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_streamWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_streamWeights() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->streamWeights(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_streamWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status streamWeights(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::params::Parameters, ::params::Parameters>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* streamWeights(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* streamWeights(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_sendWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_sendWeights() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->sendWeights(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_sendWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendWeights(::grpc::ServerContext* /*context*/, const ::params::Parameters* /*request*/, ::grpc::ServerWriter< ::params::Parameters>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* sendWeights(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* sendWeights(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_sendWeights : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_sendWeights() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::params::Parameters, ::params::Parameters>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::params::Parameters, ::params::Parameters>* streamer) {
                       return this->StreamedsendWeights(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_sendWeights() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendWeights(::grpc::ServerContext* /*context*/, const ::params::Parameters* /*request*/, ::grpc::ServerWriter< ::params::Parameters>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedsendWeights(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::params::Parameters,::params::Parameters>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_sendWeights<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_sendWeights<Service > StreamedService;
};

}  // namespace params


#endif  // GRPC_sendReceiveWeights_2eproto__INCLUDED
