// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sendReceiveWeights.proto

#include "sendReceiveWeights.pb.h"
#include "sendReceiveWeights.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace params {

static const char* WeightsPasser_method_names[] = {
  "/params.WeightsPasser/sendWeights",
};

std::unique_ptr< WeightsPasser::Stub> WeightsPasser::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WeightsPasser::Stub> stub(new WeightsPasser::Stub(channel, options));
  return stub;
}

WeightsPasser::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_sendWeights_(WeightsPasser_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::params::Parameters>* WeightsPasser::Stub::sendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request) {
  return ::grpc::internal::ClientReaderFactory< ::params::Parameters>::Create(channel_.get(), rpcmethod_sendWeights_, context, request);
}

void WeightsPasser::Stub::experimental_async::sendWeights(::grpc::ClientContext* context, const ::params::Parameters* request, ::grpc::experimental::ClientReadReactor< ::params::Parameters>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::params::Parameters>::Create(stub_->channel_.get(), stub_->rpcmethod_sendWeights_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::params::Parameters>* WeightsPasser::Stub::AsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::params::Parameters>::Create(channel_.get(), cq, rpcmethod_sendWeights_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::params::Parameters>* WeightsPasser::Stub::PrepareAsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::Parameters& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::params::Parameters>::Create(channel_.get(), cq, rpcmethod_sendWeights_, context, request, false, nullptr);
}

WeightsPasser::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeightsPasser_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< WeightsPasser::Service, ::params::Parameters, ::params::Parameters>(
          [](WeightsPasser::Service* service,
             ::grpc::ServerContext* ctx,
             const ::params::Parameters* req,
             ::grpc::ServerWriter<::params::Parameters>* writer) {
               return service->sendWeights(ctx, req, writer);
             }, this)));
}

WeightsPasser::Service::~Service() {
}

::grpc::Status WeightsPasser::Service::sendWeights(::grpc::ServerContext* context, const ::params::Parameters* request, ::grpc::ServerWriter< ::params::Parameters>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace params

