// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sendReceiveWeights.proto

#include "sendReceiveWeights.pb.h"
#include "sendReceiveWeights.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace params {

static const char* weightsPasser_method_names[] = {
  "/params.weightsPasser/sendWeights",
};

std::unique_ptr< weightsPasser::Stub> weightsPasser::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< weightsPasser::Stub> stub(new weightsPasser::Stub(channel, options));
  return stub;
}

weightsPasser::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_sendWeights_(weightsPasser_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status weightsPasser::Stub::sendWeights(::grpc::ClientContext* context, const ::params::WeightsToServer& request, ::params::WeightsToClient* response) {
  return ::grpc::internal::BlockingUnaryCall< ::params::WeightsToServer, ::params::WeightsToClient, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_sendWeights_, context, request, response);
}

void weightsPasser::Stub::experimental_async::sendWeights(::grpc::ClientContext* context, const ::params::WeightsToServer* request, ::params::WeightsToClient* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::params::WeightsToServer, ::params::WeightsToClient, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sendWeights_, context, request, response, std::move(f));
}

void weightsPasser::Stub::experimental_async::sendWeights(::grpc::ClientContext* context, const ::params::WeightsToServer* request, ::params::WeightsToClient* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sendWeights_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::params::WeightsToClient>* weightsPasser::Stub::PrepareAsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::WeightsToServer& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::params::WeightsToClient, ::params::WeightsToServer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_sendWeights_, context, request);
}

::grpc::ClientAsyncResponseReader< ::params::WeightsToClient>* weightsPasser::Stub::AsyncsendWeightsRaw(::grpc::ClientContext* context, const ::params::WeightsToServer& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsendWeightsRaw(context, request, cq);
  result->StartCall();
  return result;
}

weightsPasser::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      weightsPasser_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< weightsPasser::Service, ::params::WeightsToServer, ::params::WeightsToClient, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](weightsPasser::Service* service,
             ::grpc::ServerContext* ctx,
             const ::params::WeightsToServer* req,
             ::params::WeightsToClient* resp) {
               return service->sendWeights(ctx, req, resp);
             }, this)));
}

weightsPasser::Service::~Service() {
}

::grpc::Status weightsPasser::Service::sendWeights(::grpc::ServerContext* context, const ::params::WeightsToServer* request, ::params::WeightsToClient* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace params

